name: JMeter Performance Test1

on:
  push:
    branches:
      - main  

jobs:
  jmeter-test:
    runs-on: windows-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    # 3. Install JMeter using Chocolatey
    - name: Install JMeter
      run: choco install jmeter -y

    # 4. Verify JMeter Installation
    - name: Verify JMeter Installation
      run: jmeter -v

    # 5. Create JMeter Test Plan
    - name: Create JMeter Test Plan
      run: |
        New-Item -Path reports -ItemType Directory -Force
        @"
        <?xml version="1.0" encoding="UTF-8"?>
        <jmeterTestPlan version="1.2" properties="5.0" jmeter="5.6.3">
          <hashTree>
            <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="test_plan_powerapps">
              <boolProp name="TestPlan.functional_mode">true</boolProp>
              <boolProp name="TestPlan.serialize_threadgroups">true</boolProp>
              <boolProp name="TestPlan.tearDown_on_shutdown">true</boolProp>
              <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="User Defined Variables">
                <collectionProp name="Arguments.arguments"/>
              </elementProp>
            </TestPlan>
            <hashTree>
              <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Users">
                <intProp name="ThreadGroup.num_threads">100</intProp>
                <intProp name="ThreadGroup.ramp_time">10</intProp>
                <boolProp name="ThreadGroup.same_user_on_next_iteration">false</boolProp>
                <stringProp name="ThreadGroup.on_sample_error">stoptest</stringProp>
                <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller">
                  <stringProp name="LoopController.loops">1</stringProp>
                  <boolProp name="LoopController.continue_forever">false</boolProp>
                </elementProp>
              </ThreadGroup>
              <hashTree>
                <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP Request">
                  <stringProp name="HTTPSampler.domain">farmhanddev.crm4.dynamics.com</stringProp>
                  <stringProp name="HTTPSampler.path">/main.aspx?appid=2d6211aa-bb7b-4184-9f49-e27234313d5a</stringProp>
                  <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
                  <stringProp name="HTTPSampler.method">GET</stringProp>
                  <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
                  <boolProp name="HTTPSampler.postBodyRaw">false</boolProp>
                  <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables">
                    <collectionProp name="Arguments.arguments"/>
                  </elementProp>
                </HTTPSamplerProxy>
                <hashTree>
                  <!-- Add your ResultCollectors here as needed -->
                  <!-- Example ResultCollector -->
                  <ResultCollector guiclass="SummaryReport" testclass="ResultCollector" testname="Summary Report">
                    <boolProp name="ResultCollector.error_logging">false</boolProp>
                    <objProp>
                      <name>saveConfig</name>
                      <value class="SampleSaveConfiguration">
                        <time>true</time>
                        <latency>true</latency>
                        <timestamp>true</timestamp>
                        <success>true</success>
                        <label>true</label>
                        <code>true</code>
                        <message>true</message>
                        <threadName>true</threadName>
                        <dataType>true</dataType>
                        <encoding>false</encoding>
                        <assertions>true</assertions>
                        <subresults>true</subresults>
                        <responseData>false</responseData>
                        <samplerData>false</samplerData>
                        <xml>false</xml>
                        <fieldNames>true</fieldNames>
                        <responseHeaders>false</responseHeaders>
                        <requestHeaders>false</requestHeaders>
                        <responseDataOnError>false</responseDataOnError>
                        <saveAssertionResultsFailureMessage>true</saveAssertionResultsFailureMessage>
                        <assertionsResultsToSave>0</assertionsResultsToSave>
                        <bytes>true</bytes>
                        <sentBytes>true</sentBytes>
                        <url>true</url>
                        <threadCounts>true</threadCounts>
                        <idleTime>true</idleTime>
                        <connectTime>true</connectTime>
                      </value>
                    </objProp>
                    <stringProp name="filename">summary_report.jtl</stringProp>
                  </ResultCollector>
                  <hashTree/>
                  <!-- Add other ResultCollectors as needed -->
                </hashTree>
              </hashTree>
            </hashTree>
          </hashTree>
        </jmeterTestPlan>
        "@ | Set-Content -Path test_plan.jmx -Force

    # 6. Run JMeter Test
    - name: Run JMeter Test
      run: |
        jmeter -n -t test_plan.jmx -l reports/results.jtl -j reports/jmeter.log -e -o reports/html

    # 7. Archive Test Results
    - name: Archive Test Results
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-reports
        path: reports/

    # 8. Display HTML Report
    - name: Display HTML Report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        user_name: "L00179076"
        user_email: "L00179076@atu.ie"
        publish_dir: ./reports/html
        publish_branch: gh-pages
