name: Pipe-Line
# Export solution from DEV environment
# unpack it and prepare, commit and push a git branch with the changes
# Then, run Selenium tests on Windows with Firefox

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Who-Am-I Action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://farmhanddev.crm4.dynamics.com/'
        user-name: 'slilly@FarmhandCRM.onmicrosoft.com'
        password-secret: ${{ secrets.password }}

    - name: Export Solution Action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://farmhanddev.crm4.dynamics.com/'
        user-name: 'slilly@FarmhandCRM.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: BPFCustomizations
        solution-output-file: out/exported/ALMLab.zip

    - name: Unpack Solution Action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/ALMLab.zip
        solution-folder: out/solutions/ALMLab
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Branch Solution and Prepare for Pull Request
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/ALMLab
        solution-target-folder: solutions/ALMLab
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true

  selenium-tests:
    runs-on: windows-latest
    needs: export-from-dev

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Install Firefox
      run: choco install firefox --no-progress --confirm

    - name: Download and Install GeckoDriver
      run: |
        $geckoVersion = (Invoke-RestMethod -Uri "https://api.github.com/repos/mozilla/geckodriver/releases/latest").tag_name.TrimStart('v')
        Invoke-WebRequest -Uri "https://github.com/mozilla/geckodriver/releases/download/v$geckoVersion/geckodriver-v$geckoVersion-win64.zip" -OutFile "geckodriver.zip"
        Expand-Archive geckodriver.zip -DestinationPath "C:\tools\geckodriver"
        $env:PATH += ";C:\tools\geckodriver"

    - name: Add GeckoDriver to PATH
      run: echo "C:\tools\geckodriver" | Out-File -Append -FilePath $env:GITHUB_PATH

    - name: Run Selenium Tests
      run: node seleniumTest1.js



  failure-response-test:
    runs-on: windows-latest
    needs: selenium-tests
    if: ${{ failure() }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set JMeter Path
      run: |
        $jmeterPath = "C:\Users\TDA\Downloads\apache-jmeter-5.6.3\bin"
        [Environment]::SetEnvironmentVariable("JMETER_HOME", $jmeterPath, [System.EnvironmentVariableTarget]::Machine)
        [Environment]::SetEnvironmentVariable("PATH", "$env:PATH;$jmeterPath", [System.EnvironmentVariableTarget]::Machine)
        Write-Host "JMeter path is $jmeterPath"

    - name: Create Failure Response Test Plan
      run: |
        New-Item -Path failure_response_reports -ItemType Directory -Force
        @"
        <?xml version="1.0" encoding="UTF-8"?>
        <jmeterTestPlan version="1.2" properties="5.0" jmeter="5.6.3">
          <hashTree>
            <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Failure Response Test Plan">
              <boolProp name="TestPlan.functional_mode">true</boolProp>
              <boolProp name="TestPlan.serialize_threadgroups">true</boolProp>
              <boolProp name="TestPlan.tearDown_on_shutdown">true</boolProp>
            </TestPlan>
            <hashTree>
              <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Thread Group">
                <stringProp name="ThreadGroup.num_threads">50</stringProp>
                <stringProp name="ThreadGroup.ramp_time">5</stringProp>
                <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller">
                  <stringProp name="LoopController.loops">5</stringProp>
                </elementProp>
              </ThreadGroup>
              <hashTree>
                <!-- Simulate failure -->
                <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="Simulate Failure">
                  <stringProp name="HTTPSampler.domain">example.com</stringProp>
                  <stringProp name="HTTPSampler.path">/simulate-failure</stringProp>
                  <stringProp name="HTTPSampler.method">GET</stringProp>
                </HTTPSamplerProxy>
                <hashTree>
                  <ResponseAssertion guiclass="AssertionGui" testclass="ResponseAssertion" testname="Check Failure Response">
                    <stringProp name="ResponseAssertion.test_field">Response Code</stringProp>
                    <stringProp name="ResponseAssertion.assertion_type">2</stringProp>
                    <collectionProp name="ResponseAssertion.field_to_check">
                      <stringProp name="404">404</stringProp>
                    </collectionProp>
                  </ResponseAssertion>
                </hashTree>
                <!-- Check continued functionality -->
                <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="Check Functionality">
                  <stringProp name="HTTPSampler.domain">example.com</stringProp>
                  <stringProp name="HTTPSampler.path">/check-functionality</stringProp>
                  <stringProp name="HTTPSampler.method">GET</stringProp>
                </HTTPSamplerProxy>
                <hashTree>
                  <ResponseAssertion guiclass="AssertionGui" testclass="ResponseAssertion" testname="Check Functionality Response">
                    <stringProp name="ResponseAssertion.test_field">Response Code</stringProp>
                    <stringProp name="ResponseAssertion.assertion_type">1</stringProp>
                    <collectionProp name="ResponseAssertion.field_to_check">
                      <stringProp name="200">200</stringProp>
                    </collectionProp>
                  </ResponseAssertion>
                </hashTree>
              </hashTree>
            </hashTree>
          </hashTree>
        </jmeterTestPlan>
        "@ | Set-Content -Path failure_response_test_plan.jmx -Force
