name: Pipe-Line
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://farmhanddev.crm4.dynamics.com/'
        user-name: 'slilly@FarmhandCRM.onmicrosoft.com'
        password-secret: ${{ secrets.password }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://farmhanddev.crm4.dynamics.com/'
        user-name: 'slilly@FarmhandCRM.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: BPFCustomizations
        solution-output-file: out/exported/ALMLab.zip

    
    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/ALMLab.zip
        solution-folder: out/solutions/ALMLab
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/ALMLab
        solution-target-folder: solutions/ALMLab
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true



  name: Run Selenium Tests on Windows with Firefox

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install Firefox
      run: choco install firefox --no-progress --confirm

    - name: Download and install GeckoDriver
      run: |
        $geckoVersion = (Invoke-RestMethod -Uri "https://api.github.com/repos/mozilla/geckodriver/releases/latest").tag_name.TrimStart('v')
        Invoke-WebRequest -Uri "https://github.com/mozilla/geckodriver/releases/download/v$geckoVersion/geckodriver-v$geckoVersion-win64.zip" -OutFile "geckodriver.zip"
        Expand-Archive geckodriver.zip -DestinationPath "C:\tools\geckodriver"
        $env:PATH += ";C:\tools\geckodriver"

    - name: Add GeckoDriver to PATH
      run: echo "C:\tools\geckodriver" | Out-File -Append -FilePath $env:GITHUB_PATH

    - name: Run Selenium tests
      run: node seleniumTest1.js
