name: Run Selenium Tests on Windows with Firefox

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install Firefox
      run: choco install firefox --no-progress --confirm

    - name: Install GeckoDriver
      run: choco install geckodriver --no-progress --confirm

    - name: Add GeckoDriver to PATH
      run: echo "C:\Program Files\geckodriver" | Out-File -Append -FilePath $env:GITHUB_PATH

    - name: Run Selenium tests
      run: node seleniumTest1.js
