
name: Selenium UI Tests

on: [push, pull_request]

jobs:
  selenium:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v1

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run Selenium tests
      run: node seleniumTest1.js
      
