name: Selenium UI Tests

on: [push, pull_request]

jobs:
  selenium:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Set up GeckoDriver
      uses: mozilla/geckodriver@v1.23.0

    - name: Set up Firefox
      uses: browser-actions/setup-firefox@v2

    - name: Run Selenium tests
      run: node seleniumTest1.js
