# .github/workflows/selenium.yml

name: Selenium UI Tests

on: [push, pull_request]

jobs:
  selenium:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run Selenium tests
      run: node seleniumTest.js
